### ISSUE TITLE
Download and add iNaturalist data to repo

### ISSUE THREAD

**Issue by coreytcallaghan** [cjroberts88/diver_fish_selectivity#3]

**Comment by cjroberts88** [comment]
inat data added, A few months old as i have to get them from mark.


Just an FYI. This data has two co-ordinates columns. 
latitude and longitude
and private latitude and private longitude

The private lat longs need a line of code to overwritt the corresponding 'normal' lat long as these lat longs have been obscured for protected species.

**Comment by coreytcallaghan** [comment]
Cool. I guess you've accomplished this easy issue ;)
